FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 80
ENV ORIGIN_HOST="*"

# Etapa de compilação
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src
COPY src/BackendAPI.csproj BackendAPI/
RUN dotnet restore "BackendAPI/BackendAPI.csproj"
COPY src BackendAPI/
WORKDIR /src/BackendAPI
RUN dotnet build "BackendAPI.csproj" -c Release -o /app/build

# Etapa de publicação
FROM build AS publish
RUN dotnet publish "BackendAPI.csproj" -c Release -o /app/publish

# Etapa final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BackendAPI.dll"]
