apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-angular
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:
      containers:
      - name: frontend-angular
        image: paulocr.azurecr.io/frontend-angular:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
