apiVersion: v1
kind: Service
metadata:
  name: frontend-angular-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
