trigger:
  - main
  - develop

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: ''
  imageRepository: 'company_sql_server'
  containerRegistry: 'paulocr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile.Prod'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile.Prod'
              tags: |
                $(tag)
