version: "3.8"

services:
  angular-frontend-app-dev:
    container_name: angular-frontend-app-dev
    build:
      dockerfile: Dockerfile.Dev
      context: .
    ports:
      - 4200:4200
    volumes:
      - .:/app

  # angular-frontend-app-prod:
  #   container_name: angular-frontend-app-prod
  #   build:
  #     dockerfile: Dockerfile.Prod
  #     context: .
  #   ports:
  #     - 3001:80
