FROM node:18.17.1-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --configuration=production

# Serve Application using Nginx Server #
FROM nginx:alpine
COPY --from=build /app/dist/angular-frontend-app/ /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
